import FreeCAD as App

def linearFromPoints(p1, p2):
    """Calculate linear equation from points.

        Calculate the slope and offset parameters of the linear equation
        of a line defined by two points.

        Linear equation:
        y = m * x + b
        m = dy / dx
        m ... Slope
        b ... Offset (point where the line intersects the y axis)
        dx/dy ... Delta x and y. Using both as a vector results
        in a non-offset direction vector.
    """
def determinant(mat, n):
    """Return the determinant of an N-matrix.

        It recursively expands the minors.
    """
