import FreeCAD as App
import draftutils.gui_utils as gui_utils
from _typeshed import Incomplete

def make_polygon(nfaces, radius: int = ..., inscribed: bool = ..., placement: Incomplete | None = ..., face: Incomplete | None = ..., support: Incomplete | None = ...):
    """makePolgon(edges,[radius],[inscribed],[placement],[face])

        Creates a polygon object with the given number of edges and radius.

        Parameters
        ----------
        edges : int
            Number of edges of the polygon.

        radius :
            Radius of the control circle.

        inscribed : bool
            Defines is the polygon is inscribed or not into the control circle.

        placement : Base.Placement
            If placement is given, it is used.

        face : bool
            If face is True, the resulting shape is displayed as a face,
            otherwise as a wireframe.

        support :
            TODO: Describe
    """
def makePolygon(nfaces, radius: int = ..., inscribed: bool = ..., placement: Incomplete | None = ..., face: Incomplete | None = ..., support: Incomplete | None = ...):
    """makePolgon(edges,[radius],[inscribed],[placement],[face])

        Creates a polygon object with the given number of edges and radius.

        Parameters
        ----------
        edges : int
            Number of edges of the polygon.

        radius :
            Radius of the control circle.

        inscribed : bool
            Defines is the polygon is inscribed or not into the control circle.

        placement : Base.Placement
            If placement is given, it is used.

        face : bool
            If face is True, the resulting shape is displayed as a face,
            otherwise as a wireframe.

        support :
            TODO: Describe
    """
