import FreeCAD as App
import draftutils.gui_utils as gui_utils
from _typeshed import Incomplete

def make_shape2dview(baseobj, projectionVector: Incomplete | None = ..., facenumbers: list = ...):
    """make_shape2dview(object, [projectionVector], [facenumbers])

        Add a 2D shape to the document, which is a 2D projection of the given object.

        Parameters
        ----------
        object :
            TODO: Describe

        projectionVector : Base.Vector
            Custom vector for the projection

        facenumbers : [] TODO: Describe
            A list of face numbers to be considered in individual faces mode.
    """
def makeShape2DView(baseobj, projectionVector: Incomplete | None = ..., facenumbers: list = ...):
    """make_shape2dview(object, [projectionVector], [facenumbers])

        Add a 2D shape to the document, which is a 2D projection of the given object.

        Parameters
        ----------
        object :
            TODO: Describe

        projectionVector : Base.Vector
            Custom vector for the projection

        facenumbers : [] TODO: Describe
            A list of face numbers to be considered in individual faces mode.
    """
