import FreeCAD as App
import draftutils.gui_utils as gui_utils
from _typeshed import Incomplete

def make_ellipse(majradius, minradius, placement: Incomplete | None = ..., face: Incomplete | None = ..., support: Incomplete | None = ...):
    """make_ellipse(majradius, minradius, [placement], [face], [support])

        Makes an ellipse with the given major and minor radius, and optionally
        a placement.

        Parameters
        ----------
        majradius :
            Major radius of the ellipse.

        minradius :
            Minor radius of the ellipse.

        placement : Base.Placement
            If a placement is given, it is used.

        face : Bool
            If face is False, the rectangle is shown as a wireframe,
            otherwise as a face.

        support :
            TODO: Describe.
    """
def makeEllipse(majradius, minradius, placement: Incomplete | None = ..., face: Incomplete | None = ..., support: Incomplete | None = ...):
    """make_ellipse(majradius, minradius, [placement], [face], [support])

        Makes an ellipse with the given major and minor radius, and optionally
        a placement.

        Parameters
        ----------
        majradius :
            Major radius of the ellipse.

        minradius :
            Minor radius of the ellipse.

        placement : Base.Placement
            If a placement is given, it is used.

        face : Bool
            If face is False, the rectangle is shown as a wireframe,
            otherwise as a face.

        support :
            TODO: Describe.
    """
