import FreeCAD as App
import draftutils.gui_utils as gui_utils

def make_shapestring(String, FontFile, Size: int = ..., Tracking: int = ...):
    """ShapeString(Text,FontFile,[Height],[Track])

        Turns a text string into a Compound Shape

        Parameters
        ----------
        majradius :
            Major radius of the ellipse.

    """
def makeShapeString(String, FontFile, Size: int = ..., Tracking: int = ...):
    """ShapeString(Text,FontFile,[Height],[Track])

        Turns a text string into a Compound Shape

        Parameters
        ----------
        majradius :
            Major radius of the ellipse.

    """
