import FreeCAD as App
import draftutils.gui_utils as gui_utils

def make_facebinder(selectionset, name: str = ...):
    '''make_facebinder(selectionset, [name])

        Creates a Facebinder object from a selection set.

        Parameters
        ----------
        selectionset :
            Only faces will be added.

        name : string (default = "Facebinder")
            Name of the created object
    '''
def makeFacebinder(selectionset, name: str = ...):
    '''make_facebinder(selectionset, [name])

        Creates a Facebinder object from a selection set.

        Parameters
        ----------
        selectionset :
            Only faces will be added.

        name : string (default = "Facebinder")
            Name of the created object
    '''
