import FreeCAD as App
import draftobjects.base
from draftobjects.base import DraftObject as DraftObject

class Facebinder(draftobjects.base.DraftObject):
    def __init__(self, obj) -> None: ...
    def execute(self, obj): ...
    def onChanged(self, obj, prop): ...
    def addSubobjects(self, obj, facelinks):
        """adds facelinks to this facebinder"""

class _Facebinder(draftobjects.base.DraftObject):
    def __init__(self, obj) -> None: ...
    def execute(self, obj): ...
    def onChanged(self, obj, prop): ...
    def addSubobjects(self, obj, facelinks):
        """adds facelinks to this facebinder"""
