import FreeCAD as App
import draftobjects.base
import draftutils.utils as utils
from draftobjects.base import DraftObject as DraftObject

class ShapeString(draftobjects.base.DraftObject):
    def __init__(self, obj) -> None: ...
    def execute(self, obj): ...
    def onChanged(self, obj, prop): ...
    def makeFaces(self, wireChar): ...
    def makeGlyph(self, facelist):
        """ turn list of simple contour faces into a compound shape representing a glyph """

class _ShapeString(draftobjects.base.DraftObject):
    def __init__(self, obj) -> None: ...
    def execute(self, obj): ...
    def onChanged(self, obj, prop): ...
    def makeFaces(self, wireChar): ...
    def makeGlyph(self, facelist):
        """ turn list of simple contour faces into a compound shape representing a glyph """
