import DraftVecUtils as DraftVecUtils
import FreeCAD as App

def join_wires(wires, joinAttempts: int = ...):
    """join_wires(objects): merges a set of wires where possible, if any of those
        wires have a coincident start and end point"""
def joinWires(wires, joinAttempts: int = ...):
    """join_wires(objects): merges a set of wires where possible, if any of those
        wires have a coincident start and end point"""
def join_two_wires(wire1, wire2):
    """join_two_wires(object, object): joins two wires if they share a common
        point as a start or an end.
    """
def joinTwoWires(wire1, wire2):
    """join_two_wires(object, object): joins two wires if they share a common
        point as a start or an end.
    """
